url: "http://0.0.0.0:4000"
baseurl: ""
#############################################
# Assets configuration
#############################################

# extensionless url allows to automatically switch
# to current page protocol (http or https)
# to avoid mixed content problems
# distant-assets-url: "//swcarpentry.github.io/styles/"

# repository url
# NO TRAILING SLASH
distantAssetsUrl: "http://swctasks.github.io"

# path : "/styles"
# NO TRAILING SLASH
# Leave empty if assets are at the root of the domain
distantAssetsPath: "/styles/assets"
