#===============================================================================
# This config-file is only needed for development. Instead of changing the url
# everytime you work locally on the project, you start both config-files, overwriting
# the first one with the development variables needed.
#
# Start development with "$ bundle exec jekyll serve --config _config.yml,_config_dev.yml"
#===============================================================================

# Website domain (no trailing slash).
# This serves locally on port 4000.
domain: "http://0.0.0.0:4000"

# Base URL below the domain (no trailing slash).
# This is an empty string to serve directly under "/".
baseurl: ""

# Expand SASS for development.
# http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
sass:
  style: :expanded
  line_numbers: true
  # trace_selectors: true
  # debug_info: true
  # FUTURE https://github.com/jekyll/jekyll-sass-converter/issues/12
  sourcemap: true
