#===============================================================================
# Services listed in footer
#===============================================================================

- name: "Contact"
  url: "/contact/"
  title: "Contact"
- name: "RSS"
  url: "/feed.xml"
  title: "Subscribe to RSS Feed"
- name: "sitemap.xml"
  url: "/sitemap.xml"
  title: "Sitemap for Google Webmaster Tools"
- name: "License"
  url: "/license/"
  title: "License"
